name: fluig_oauth1
description: A application to connect any application in flutter to TOTVS Fluig Platform
version: 1.1.0
homepage: https://github.com/aldoiguerra/dart_fluig_oauth1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  crypto: ^3.0.1
  http: ^0.13.4

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.2
