name: fluig_oauth1
description: A starting point for Dart libraries or applications.
version: 1.0.1
homepage: https://github.com/aldoiguerra/dart_fluig_oauth1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  crypto: ^2.0.0
  http: '>=0.11.0 < 0.13.0'

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
